// frontend/src/components/Header.vue
<template>
  <header class="navbar min-h-12 h-12 bg-base-200 border-b border-base-content/10 px-3 md:px-4 flex items-center justify-between text-xs font-mono select-none z-40 transition-colors">
    <!-- Left Section: Brand, WS status, Active bot badge -->
    <div class="flex items-center gap-2 md:gap-4 overflow-hidden">
      <div class="flex items-center gap-2 font-bold tracking-wider text-base-content shrink-0">
        <Terminal class="w-4 h-4 text-primary animate-pulse" />
        <span class="hidden sm:inline">NujinSkills_CORE</span>
      </div>

      <!-- Live WS Status Badge -->
      <div class="badge badge-sm gap-1.5 py-2.5 px-2 font-semibold border-base-content/10 bg-base-300 shrink-0">
        <span class="w-2 h-2 rounded-full" :class="isConnected ? 'bg-success animate-ping' : 'bg-warning'" />
        <span :class="isConnected ? 'text-success font-bold' : 'text-warning'">
          {{ isConnected ? 'ONLINE' : 'OFFLINE' }}
        </span>
      </div>

      <!-- Active Strategies Counter Badge -->
      <div 
        class="badge badge-sm gap-1.5 py-2.5 px-2 border transition-colors cursor-pointer hidden sm:flex shrink-0"
        :class="activeCount > 0 ? 'badge-success badge-outline bg-success/10 text-success' : 'badge-neutral bg-base-300 text-base-content/60'"
        :title="activeCount > 0 ? `Active: ${effectiveActiveStrategies.join(', ')}` : 'No bot active'"
      >
        <span class="w-1.5 h-1.5 rounded-full" :class="activeCount > 0 ? 'bg-success animate-pulse' : 'bg-base-content/40'" />
        <span class="font-bold text-[10px] uppercase">Active:</span>
        <span class="font-bold font-mono">{{ activeCount }}</span>
        <span v-if="activeCount > 0 && primaryActiveStrat" class="text-[10px] opacity-80 truncate max-w-[120px] hidden lg:inline">
          ({{ primaryActiveStrat }}{{ activeCount > 1 ? ` +${activeCount - 1}` : '' }})
        </span>
      </div>

      <!-- Viewing indicator -->
      <div 
        v-if="isViewingDifferent" 
        class="badge badge-sm badge-info badge-outline bg-info/10 gap-1 py-2.5 px-2 text-[10px] hidden xl:flex shrink-0"
        :title="`Inspecting ${cleanViewingName}`"
      >
        <Eye class="w-3 h-3 text-info" />
        <span class="opacity-70 uppercase font-bold text-[9px]">Viewing:</span>
        <span class="font-bold truncate max-w-[140px]">{{ cleanViewingName }}</span>
      </div>
    </div>

    <!-- Center/Right: Navigation Tabs & Controls -->
    <div class="flex items-center gap-1.5 md:gap-2 shrink-0">
      <!-- Navigation Button Group -->
      <div class="join">
        <button
          @click="emit('update:activeScreen', 'CHART')"
          class="btn btn-xs join-item font-mono tracking-tight"
          :class="activeScreen === 'CHART' ? 'btn-primary text-primary-content font-bold shadow' : 'btn-ghost text-base-content/70'"
          title="Live Candlestick Chart (F1)"
        >
          <BarChart2 class="w-3.5 h-3.5 mr-0.5" />
          <span class="hidden md:inline">Chart</span> (F1)
        </button>

        <button
          @click="emit('update:activeScreen', 'AGENT_DECK')"
          class="btn btn-xs join-item font-mono tracking-tight"
          :class="activeScreen === 'AGENT_DECK' ? 'btn-primary text-primary-content font-bold shadow' : 'btn-ghost text-base-content/70'"
          title="Signal Deck & Bot Telemetry (F2)"
        >
          <Send class="w-3.5 h-3.5 mr-0.5" />
          <span class="hidden md:inline">Signals</span> (F2)
        </button>

        <button
          @click="emit('update:activeScreen', 'BACKTEST')"
          class="btn btn-xs join-item font-mono tracking-tight"
          :class="activeScreen === 'BACKTEST' ? 'btn-primary text-primary-content font-bold shadow' : 'btn-ghost text-base-content/70'"
          title="Backtest Analytics & Cynic Audit (F3)"
        >
          <ShieldCheck class="w-3.5 h-3.5 mr-0.5" />
          <span class="hidden md:inline">Backtest</span> (F3)
        </button>

        <button
          @click="emit('update:activeScreen', 'STRATEGY_MANAGER')"
          class="btn btn-xs join-item font-mono tracking-tight"
          :class="activeScreen === 'STRATEGY_MANAGER' ? 'btn-secondary text-secondary-content font-bold shadow' : 'btn-ghost text-base-content/70'"
          title="Strategy Lifecycle Manager & Portfolio (F4)"
        >
          <Layers class="w-3.5 h-3.5 mr-0.5" />
          <span class="hidden md:inline">Strategies</span> (F4)
        </button>
      </div>

      <!-- Divider -->
      <div class="divider divider-horizontal mx-0.5 my-2 hidden sm:flex" />

      <!-- Local Machine Clock -->
      <div 
        class="hidden lg:flex items-center gap-1.5 px-2 py-1 rounded bg-base-300 border border-base-content/10 text-[11px]"
        :title="`Local Time: ${localTimeStr}`"
      >
        <Clock class="w-3.5 h-3.5 text-accent" />
        <span class="font-bold text-success">{{ localTimeStr }}</span>
      </div>

      <!-- Audio Tone Alerts Control -->
      <div class="join border border-base-content/10 rounded-btn overflow-hidden bg-base-300">
        <button
          @click="handleToggleSound"
          class="btn btn-xs btn-ghost join-item px-2 text-[10px] font-bold uppercase"
          :class="soundEnabled ? 'text-success' : 'text-base-content/50'"
          :title="soundEnabled ? 'Audio Chimes: ON (Click to mute)' : 'Audio Chimes: MUTED (Click to unmute)'"
        >
          <Volume2 v-if="soundEnabled" class="w-3.5 h-3.5 text-success" />
          <VolumeX v-else class="w-3.5 h-3.5 text-base-content/40" />
          <span class="hidden 2xl:inline ml-1">{{ soundEnabled ? 'Tone On' : 'Muted' }}</span>
        </button>
        <button
          @click="handleTestSound"
          class="btn btn-xs btn-ghost join-item border-l border-base-content/10 px-1.5 text-[9px] text-base-content/70 hover:text-base-content uppercase font-bold"
          title="Preview Harmonic Signal Tone"
        >
          Test
        </button>
      </div>

      <!-- Theme Switcher Button -->
      <button
        @click="toggleTheme"
        class="btn btn-xs btn-circle btn-ghost border border-base-content/10"
        :title="`Switch to ${isDark ? 'Light' : 'Dark'} Mode`"
      >
        <Sun v-if="isDark" class="w-3.5 h-3.5 text-warning" />
        <Moon v-else class="w-3.5 h-3.5 text-secondary" />
      </button>
    </div>
  </header>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue';
import {
  Terminal,
  BarChart2,
  ShieldCheck,
  Sun,
  Moon,
  Send,
  Layers,
  Eye,
  Clock,
  Volume2,
  VolumeX,
} from 'lucide-vue-next';
import { isAudioEnabled, toggleAudioEnabled, testSignalTone } from '../utils/audio';

const props = defineProps<{
  activeScreen: 'CHART' | 'AGENT_DECK' | 'BACKTEST' | 'STRATEGY_MANAGER';
  isConnected: boolean;
  theme: 'dark' | 'light';
  activeStrategy?: string;
  activeBots?: string[];
  viewingStrategy?: string;
}>();

const emit = defineEmits<{
  (e: 'update:activeScreen', screen: 'CHART' | 'AGENT_DECK' | 'BACKTEST' | 'STRATEGY_MANAGER'): void;
  (e: 'update:theme', theme: 'dark' | 'light'): void;
}>();

const isDark = computed(() => props.theme === 'dark');

// Live machine clock
const localTimeStr = ref('');
let clockTimer: any = null;

const updateClock = () => {
  const now = new Date();
  const timePart = now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false });
  const tzPart = new Intl.DateTimeFormat('en-US', { timeZoneName: 'short' }).formatToParts(now).find((p) => p.type === 'timeZoneName')?.value || '';
  localTimeStr.value = `${timePart} ${tzPart}`;
};

// Sound notification preference
const soundEnabled = ref(isAudioEnabled());

const handleToggleSound = () => {
  soundEnabled.value = toggleAudioEnabled();
};

const handleTestSound = (e: MouseEvent) => {
  e.stopPropagation();
  testSignalTone('BUY');
};

const toggleTheme = () => {
  const next = isDark.value ? 'light' : 'dark';
  emit('update:theme', next);
  document.documentElement.setAttribute('data-theme', next);
};

// Strategy active counts & viewing state
const effectiveActiveStrategies = computed(() => {
  if (props.activeBots && props.activeBots.length > 0) {
    return props.activeBots;
  }
  return props.activeStrategy ? [props.activeStrategy] : [];
});

const activeCount = computed(() => effectiveActiveStrategies.value.length);
const primaryActiveStrat = computed(() => (activeCount.value > 0 ? effectiveActiveStrategies.value[0].replace('.py', '') : null));

const cleanViewingName = computed(() => (props.viewingStrategy ? props.viewingStrategy.replace('.py', '') : ''));
const isViewingDifferent = computed(() => {
  return Boolean(
    cleanViewingName.value &&
      (!primaryActiveStrat.value || cleanViewingName.value.toLowerCase() !== primaryActiveStrat.value.toLowerCase())
  );
});

onMounted(() => {
  updateClock();
  clockTimer = setInterval(updateClock, 1000);
});

onUnmounted(() => {
  if (clockTimer) clearInterval(clockTimer);
});
</script>

// frontend/src/components/Header.tsx
import React, { useState, useEffect } from 'react';
import { Terminal, BarChart2, ShieldCheck, Sun, Moon, Send, Layers, Eye, Clock, Volume2, VolumeX } from 'lucide-react';
import { isAudioEnabled, toggleAudioEnabled, testSignalTone } from '../utils/audio';

interface HeaderProps {
  activeScreen: 'CHART' | 'AGENT_DECK' | 'BACKTEST' | 'STRATEGY_MANAGER';
  setActiveScreen: (screen: 'CHART' | 'AGENT_DECK' | 'BACKTEST' | 'STRATEGY_MANAGER') => void;
  isConnected: boolean;
  theme: 'dark' | 'light';
  setTheme: (theme: 'dark' | 'light') => void;
  activeStrategy?: string;
  activeBots?: string[];
  viewingStrategy?: string;
}

export const Header: React.FC<HeaderProps> = ({
  activeScreen,
  setActiveScreen,
  isConnected,
  theme,
  setTheme,
  activeStrategy,
  activeBots = [],
  viewingStrategy,
}) => {
  const isDark = theme === 'dark';

  // Live Machine Local Time state
  const [localTimeStr, setLocalTimeStr] = useState<string>('');
  useEffect(() => {
    const updateTime = () => {
      const now = new Date();
      const timePart = now.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false });
      const tzPart = new Intl.DateTimeFormat('en-US', { timeZoneName: 'short' }).formatToParts(now).find(p => p.type === 'timeZoneName')?.value || '';
      setLocalTimeStr(`${timePart} ${tzPart}`);
    };
    updateTime();
    const timer = setInterval(updateTime, 1000);
    return () => clearInterval(timer);
  }, []);

  // Audio tone notification state
  const [soundEnabled, setSoundEnabled] = useState<boolean>(isAudioEnabled());
  useEffect(() => {
    const handleToggle = (e: any) => {
      if (e?.detail?.enabled !== undefined) {
        setSoundEnabled(e.detail.enabled);
      }
    };
    window.addEventListener('edgeminer-sound-toggled', handleToggle);
    return () => window.removeEventListener('edgeminer-sound-toggled', handleToggle);
  }, []);

  const handleToggleSound = () => {
    const next = toggleAudioEnabled();
    setSoundEnabled(next);
  };

  const handleTestSound = (e: React.MouseEvent) => {
    e.stopPropagation();
    testSignalTone('BUY');
  };

  // Truly activated live strategies within the bot (status: ACTIVE_LIVE)
  const effectiveActiveStrategies = (activeBots && activeBots.length > 0)
    ? activeBots
    : (activeStrategy ? [activeStrategy] : []);

  const activeCount = effectiveActiveStrategies.length;
  const primaryActiveStrat = activeCount > 0 ? effectiveActiveStrategies[0].replace('.py', '') : null;

  // Currently viewed / inspected strategy (e.g. In Chart or Backtest)
  const cleanViewingName = viewingStrategy ? viewingStrategy.replace('.py', '') : '';
  const isViewingDifferent = Boolean(
    cleanViewingName &&
    (!primaryActiveStrat || cleanViewingName.toLowerCase() !== primaryActiveStrat.toLowerCase())
  );

  return (
    <header className={`h-12 border-b px-4 flex items-center justify-between text-xs font-mono select-none relative z-40 transition-colors ${
      isDark ? 'bg-[#161b22] border-[#30363d] text-white' : 'bg-white border-slate-200 text-slate-800'
    }`}>
      <div className="flex items-center gap-4">
        <div className="flex items-center gap-2 font-bold tracking-wide">
          <Terminal className="w-4 h-4 text-emerald-500" />
          <span>NujinSkills_CORE</span>
        </div>

        <div className={`flex items-center gap-2 px-2.5 py-1 rounded border ${
          isDark ? 'bg-[#0d1117] border-[#30363d]' : 'bg-slate-50 border-slate-200'
        }`}>
          <span className={`w-2 h-2 rounded-full ${isConnected ? 'bg-emerald-500 animate-pulse' : 'bg-amber-500'}`} />
          <span className={isConnected ? 'text-emerald-500 font-semibold' : 'text-amber-500'}>
            {isConnected ? 'LIVE_WS_BUS::ONLINE' : 'STANDALONE_OFFLINE'}
          </span>
        </div>

        {/* Active strategies total count badge */}
        <div
          title={
            activeCount > 0
              ? `Active strategies executing in bot: ${effectiveActiveStrategies.map((b) => b.replace('.py', '')).join(', ')}`
              : 'No strategies currently active in bot'
          }
          className={`flex items-center gap-1.5 px-2.5 py-1 rounded border transition-colors ${
            activeCount > 0
              ? (isDark ? 'bg-emerald-950/40 border-emerald-800/80 text-emerald-300' : 'bg-emerald-50 border-emerald-300 text-emerald-900')
              : (isDark ? 'bg-[#0d1117] border-slate-800 text-slate-500' : 'bg-slate-100 border-slate-300 text-slate-500')
          }`}
        >
          <span className={`w-1.5 h-1.5 rounded-full shrink-0 ${
            activeCount > 0 ? 'bg-emerald-400 animate-pulse' : 'bg-slate-500'
          }`} />
          <span className={`text-[10px] uppercase font-bold ${
            activeCount > 0 ? (isDark ? 'text-emerald-500' : 'text-emerald-700') : 'text-slate-500'
          }`}>
            Active Strategies:
          </span>
          <span className={`font-bold text-[11px] flex items-center gap-1 ${
            activeCount > 0 ? 'text-emerald-400' : 'text-slate-400'
          }`}>
            <span>{activeCount}</span>
            {activeCount > 0 && primaryActiveStrat && (
              <span className="text-[10px] text-emerald-500/80 font-normal truncate max-w-[200px] hidden md:inline">
                ({primaryActiveStrat}{activeCount > 1 ? ` +${activeCount - 1}` : ''})
              </span>
            )}
          </span>
        </div>

        {/* Viewing / Inspecting indicator if different from active bot */}
        {isViewingDifferent && (
          <div
            title={`Currently viewing ${cleanViewingName} for analysis`}
            className={`hidden sm:flex items-center gap-1.5 px-2.5 py-1 rounded border text-[10px] transition-colors ${
              isDark ? 'bg-[#161b22] border-indigo-900/60 text-slate-300' : 'bg-indigo-50 border-indigo-200 text-indigo-900'
            }`}
          >
            <Eye className="w-3 h-3 text-indigo-400" />
            <span className="text-[9px] uppercase font-bold text-slate-400">Viewing:</span>
            <span className="text-indigo-400 font-bold font-mono">{cleanViewingName}</span>
          </div>
        )}
      </div>

      <div className="flex items-center gap-2">
        {/* Navigation Tabs */}
        <button
          onClick={() => setActiveScreen('CHART')}
          className={`flex items-center gap-1.5 px-3 py-1.5 rounded transition-all font-mono ${activeScreen === 'CHART'
            ? 'bg-emerald-600 text-white font-bold shadow-md'
            : isDark ? 'bg-[#21262d] text-[#8b949e] hover:text-white border border-[#30363d]' : 'bg-slate-100 text-slate-600 hover:text-slate-900 border border-slate-300'
            }`}
        >
          <BarChart2 className="w-3.5 h-3.5" />
          <span>Chart (F1)</span>
        </button>

        <button
          onClick={() => setActiveScreen('AGENT_DECK')}
          className={`flex items-center gap-1.5 px-3 py-1.5 rounded transition-all font-mono ${activeScreen === 'AGENT_DECK'
            ? 'bg-emerald-600 text-white font-bold shadow-md'
            : isDark ? 'bg-[#21262d] text-[#8b949e] hover:text-white border border-[#30363d]' : 'bg-slate-100 text-slate-600 hover:text-slate-900 border border-slate-300'
            }`}
        >
          <Send className="w-3.5 h-3.5" />
          <span>Signals (F2)</span>

        </button>

        <button
          onClick={() => setActiveScreen('BACKTEST')}
          className={`flex items-center gap-1.5 px-3 py-1.5 rounded transition-all font-mono ${activeScreen === 'BACKTEST'
            ? 'bg-emerald-600 text-white font-bold shadow-md'
            : isDark ? 'bg-[#21262d] text-[#8b949e] hover:text-white border border-[#30363d]' : 'bg-slate-100 text-slate-600 hover:text-slate-900 border border-slate-300'
            }`}
        >
          <ShieldCheck className="w-3.5 h-3.5" />
          <span>Backtest (F3)</span>
        </button>

        <button
          onClick={() => setActiveScreen('STRATEGY_MANAGER')}
          className={`flex items-center gap-1.5 px-3 py-1.5 rounded transition-all font-mono ${activeScreen === 'STRATEGY_MANAGER'
            ? 'bg-indigo-600 text-white font-bold shadow-md'
            : isDark ? 'bg-[#21262d] text-[#8b949e] hover:text-white border border-[#30363d]' : 'bg-slate-100 text-slate-600 hover:text-slate-900 border border-slate-300'
            }`}
        >
          <Layers className="w-3.5 h-3.5" />
          <span>Strategies (F4)</span>
        </button>

        <div className="h-4 w-[1px] bg-slate-300 dark:bg-slate-700 mx-1" />

        {/* Machine Local Time Indicator */}
        <div
          title={`Machine Local Timezone: ${Intl.DateTimeFormat().resolvedOptions().timeZone}`}
          className={`hidden md:flex items-center gap-1.5 px-2.5 py-1 rounded border text-[11px] ${
            isDark ? 'bg-[#0d1117] border-[#30363d] text-slate-300' : 'bg-slate-50 border-slate-200 text-slate-700'
          }`}
        >
          <Clock className="w-3.5 h-3.5 text-sky-400" />
          <span className="font-semibold text-emerald-400">{localTimeStr}</span>
        </div>

        {/* Signal Audio Tone Alert Controls */}
        <div className={`flex items-center rounded border transition-all ${
          isDark ? 'bg-[#0d1117] border-[#30363d]' : 'bg-slate-50 border-slate-200'
        }`}>
          <button
            onClick={handleToggleSound}
            title={soundEnabled ? "Signal Tone: ON (Click to mute)" : "Signal Tone: MUTED (Click to unmute)"}
            className={`flex items-center gap-1.5 px-2 py-1 rounded-l transition-all ${
              soundEnabled
                ? (isDark ? 'text-emerald-400 hover:text-emerald-300' : 'text-emerald-600 hover:text-emerald-700')
                : 'text-slate-400 hover:text-slate-300'
            }`}
          >
            {soundEnabled ? <Volume2 className="w-3.5 h-3.5 text-emerald-400" /> : <VolumeX className="w-3.5 h-3.5 text-slate-400" />}
            <span className="text-[10px] font-bold uppercase hidden xl:inline">
              {soundEnabled ? 'Tone On' : 'Muted'}
            </span>
          </button>
          <button
            onClick={handleTestSound}
            title="Preview Signal Tone (BUY chime)"
            className={`px-1.5 py-1 text-[9px] uppercase font-bold border-l transition-all rounded-r ${
              isDark
                ? 'border-[#30363d] text-slate-400 hover:text-white hover:bg-[#21262d]'
                : 'border-slate-200 text-slate-500 hover:text-slate-800 hover:bg-slate-200'
            }`}
          >
            Test
          </button>
        </div>

        {/* System & Manual Theme Toggle Button */}
        <button
          onClick={() => setTheme(isDark ? 'light' : 'dark')}
          title={`Switch to ${isDark ? 'Light' : 'Dark'} Mode (System Detected)`}
          className={`p-1.5 rounded border transition-all ${
            isDark
              ? 'bg-[#21262d] border-[#30363d] text-amber-400 hover:text-amber-300'
              : 'bg-slate-100 border-slate-300 text-slate-700 hover:text-slate-900'
          }`}
        >
          {isDark ? <Sun className="w-4 h-4" /> : <Moon className="w-4 h-4" />}
        </button>
      </div>
    </header>
  );
};
